#This file is part of the CourseUp project.
#http://courseup.org
#
#(c) Micah Taylor
#micah@kixortech.com
#
#See http://courseup.org for license information.


CourseTitle: "Edit config.yaml to change course title"

MenuLinks:
  - MenuLinkName: Schedule
    MenuLinkURL: /
  - MenuLinkName: Edit config.yaml
    MenuLinkURL: /link/
  - MenuLinkName: To add links
    MenuLinkURL: /anotherlink/

FirstQuarterDay: 2016-03-07
LastBeforeBreak: 2016-04-01
FirstAfterBreak: 2016-04-11
############################################################
#VERY IMPORTANT NOTE:
# Uppercase chars in ClassOnWeekDays consumes two "Session:" blocks 
# in the content.md schedule source.
ClassOnWeekDays: mtWrf
############################################################
ShowPastSessions: 0
ShowFutureSessions: 5

PublicErrorMessages: false

TimeZone: America/Indiana/Indianapolis
